GoalAdd 뷰 그리기, GoalRepository에 Single 타입 적용
GunZaStation/Rabit pull request #28
Opened 2022-08-19 08:32 UTC by junu0516

close #13 #27

2022-08-19 09:08 UTC, Hansolkkim requested changes
수정 다 하시고 말씀주시면 머지하겠습니다!
고생하셨습니다 ㅎㅎ

2022-08-19 09:08 UTC, Hansolkkim commented on rabit/rabit/Goal/GoalAdd/Views/InsertField.swift
> +    }
didSet 설정으로 바로 변경하도록 하셔서 코드가 훨씬 깔끔해진것 같습니다!

2022-08-19 09:08 UTC, Hansolkkim commented on rabit/rabit/Goal/GoalAdd/Views/InsertField.swift
> +    }
사용하지 않는 메소드 제거하고 위에 초기화 생성자 내에서 호출도 지우시면 될 것 같습니다!

2022-08-19 09:08 UTC, Hansolkkim commented on rabit/rabit/Goal/GoalListViewModel.swift
> +            .flatMapLatest { viewModel, _ in
Operator 변경하신 이유가 Repository의 상태를 반영하기 위해서인가요?

2022-08-19 09:17 UTC, junu0516 commented on rabit/rabit/Goal/GoalListViewModel.swift
> +            .flatMapLatest { viewModel, _ in
넵! 나중에 Repository가 Persistence, Network 등의 계층을 바라보게 되면, 이들 계층의 상태 변화를 감지해야 될 것 같아서 최신 값을 반영하는 `flatMapLatest` 를 사용했어요!

2022-08-19 09:17 UTC, junu0516 commented on rabit/rabit/Goal/GoalAdd/Views/InsertField.swift
> +    }
앗 ㅋㅋ 깜빡했네요 바로 지우고, 구현해주신 extension 메소드 사용해볼께요!

2022-08-19 17:13 UTC, junu0516 commented
@Hansolkkim 
우선 지적해주신 주석처리한 메소드 제거하는 부분이랑, 제안하셨던 `private extension` 사용하는걸 우선 적용해서 푸시했어요!
시간되실 때 확인하시고 혹시 추가적으로 고칠 부분 있으면 말씀해주세요 ㅎㅎㅎ

2022-08-20 04:15 UTC, Hansolkkim commented
확인했습니다! 머지하도록 하겠습니다ㅎㅎ

2022-08-20 04:15 UTC, merged