PhotoEdit, ColorPicker 구현
GunZaStation/Rabit pull request #29
Opened 2022-08-19 08:57 UTC by Hansolkkim

close #24

2022-08-19 09:15 UTC, junu0516 requested changes

2022-08-19 09:15 UTC, junu0516 commented on rabit/rabit/Album/AlbumCoordinator.swift
> +private extension AlbumCoordinator {
저도 private 함수들은 이렇게 private extension 선언부에 따로 모아놓도록 바꿔볼께요!

2022-08-19 09:15 UTC, junu0516 commented on rabit/rabit/Album/AlbumCoordinator.swift
> +            .disposed(by: disposeBag)
바인딩의 방향이 '뷰모델의 속성 -> 코디네이터의 속성' 과 같은 방향인 것 같아서, 해당 부분은 뷰모델 내부에 선언하는게 어떨까 싶어요!
('코디네이터의 속성 -> 뷰모델의 속성' 과 같은 방향이면 이를 코디네이터에 명시하는게 맞는듯 합니다)

우선 떠오르는 생각은 코디네이터 참조값을 뷰모델의 bind()와 같은 메소드의 파라미터로 넘겨서, 뷰모델에서 바인딩하는 것도 괜찮아 보여요

2022-08-19 09:15 UTC, junu0516 commented on rabit/rabit/Album/AlbumViewModel.swift
> +    func bind(to navigation: AlbumNavigation) {
오 외부에서는 파라미터명이 `to` 로 나타나도록 하는게 더 이해하기 좋아보이네요 ㅋㅋ 저도 이렇게 바꿔보겠습니다.

2022-08-19 09:15 UTC, junu0516 commented on rabit/rabit/Album/PhotoEdit/PhotoEditViewController.swift
> +        imageView.translatesAutoresizingMaskIntoConstraints = false
`translatesAutoresizingMaskIntoConstraints` 속성값에 대한 접근은 SnapKit 사용하면 따로 안해도 되는 것 같더라구요!
정확하진 않은데, 우선 false로 바꾸는 로직 없이 오토레이아웃 잘 적용되면 제거해도 될듯 합니다!

2022-08-19 09:15 UTC, junu0516 commented on rabit/rabit/Album/PhotoEdit/PhotoEditViewController.swift
> +    let hexPhotoColor = PublishSubject<String>()
색상의 hex string에 대한 Observable은 뷰모델에서 가지고 있도록 하고, 뷰 컴포넌트의 rx 연산자를 통해 뷰컨트롤러-뷰모델 간 바인딩을 하는 식으로 가는게 어떨까요!??

2022-08-19 09:15 UTC, junu0516 commented on rabit/rabit/Album/PhotoEdit/PhotoEditViewController.swift
> +        view.backgroundColor = UIColor(named: "first")
이런 식으로 view.backgroundColor, navigationItem 등 뷰컨트롤러의 속성에 직접 접근해서 값을 바꾸는 로직은 뷰를 새로 추가하기 보다는, 기존의 속성을 변경하는 성격이 강한듯 해서 `setAttributes` 와 같은 함수를 따로 만들어 모아놓는 것도 괜찮을 것 같아요!

2022-08-19 09:15 UTC, junu0516 commented on rabit/rabit/Album/AlbumViewModel.swift
> +    var photoSelected: PublishRelay<Album.Item> { get }
Album.Item 타입에 외부에서 직접 접근하는 부분들이 많은 것 같아서, 아얘 Album의 하위 타입이 아닌 Album과 동등한 별도의 타입으로 두는건 어떨까요!??

2022-08-19 09:18 UTC, Hansolkkim commented on rabit/rabit/Album/AlbumCoordinator.swift
> +            .disposed(by: disposeBag)
오 그런 방법이 있었네요! 저는 이전 ViewController를 알고 있는 쪽이 Coordinator 밖에 없어서 Coordinator에서 바인딩해주도록 했는데, 그냥 ViewModel 초기화 시에 매개변수로 넘겨줘도 괜찮을 것 같네요. 수정해보겠습니다!

2022-08-19 09:18 UTC, Hansolkkim commented on rabit/rabit/Album/PhotoEdit/PhotoEditViewController.swift
> +        imageView.translatesAutoresizingMaskIntoConstraints = false
처음알았네요! 감사합니다ㅎㅎ

2022-08-20 06:23 UTC, junu0516 commented
PR 머지 확인했어요!
수정할거 있으시면 하시고 아무때나 코멘트 남겨주시면 저도 머지할께요 ㅎㅎ

2022-08-20 10:44 UTC, Hansolkkim commented
@junu0516 수정 완료했습니다! 말씀하신 부분에 대해서 수정했습니다!

2022-08-21 02:55 UTC, merged